#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# -- env --
if [[ "$OS" != "Windows_NT" ]];then
    export PATH="${PATH}:${HOME}/.local/bin"
    export XDG_CACHE_HOME="${HOME}/.cache"
    export XDG_CONFIG_HOME="${HOME}/.config"
    export XDG_DATA_HOME="${HOME}/.local/share"
    export XDG_DESKTOP_DIR="${HOME}/w"
    export XDG_DOCUMENTS_DIR="${HOME}/w"
    export XDG_DOWNLOAD_DIR="${HOME}/d"
    export XDG_MUSIC_DIR="${HOME}/m"
    export XDG_PICTURES_DIR="${HOME}/i"
    export XDG_PUBLICSHARE_DIR="${HOME}/p"
    export XDG_TEMPLATES_DIR="${HOME}/t"
    export XDG_VIDEOS_DIR="${HOME}/v"
    export DOT_PATH="${XDG_CONFIG_HOME}/d"
    export BASH_PATH="${DOT_PATH}/bash"
    . "${BASH_PATH}/startup/enviroments.bash"
    . "${BASH_PATH}/startup/alias.bash"
    . "${BASH_PATH}/startup/functions.bash"
    . "${BASH_PATH}/startup/completion.bash"
    . "${BASH_PATH}/startup/key-bindings.bash"
    . "${BASH_PATH}/startup/color_and_prompt.bash"
    . "${BASH_PATH}/startup/startx.bash"
    . "${BASH_PATH}/startup/options.bash"
    . "${BASH_PATH}/startup/config_hardware.bash"
    . "${BASH_PATH}/startup/tmux.bash"
else
    export BASH_PATH="${HOME}/.dotfiles/bash"
    . "${BASH_PATH}/enviroments/misc.bash"
    . "${BASH_PATH}/history/history.bash"
    export PATH="${PATH}:${HOME}/.script/java"
fi
