#!/usr/bin/env bash

declare url
declare path=~/w/b/b
if [[ -n "$1" ]];then
    url="$(sudo -u isbrqu xclip -selection clipboard -out)"
    [[ "$url" == http* ]] && {
        echo "$url" >> $path
    }
else
    url="$(grep '^http' $path | dmenu -l 10)"
    [[ -n "$url" ]] && {
        xdg-open "${url%% *}" &> /dev/null &
        (( $? == 0 )) && disown
    }
fi
