#!/usr/bin/env bash

declare -r brightness="0.55"
declare -a outputs=(
    "eDP-1"
    "HDMI-1"
)
declare gamma

case "$1" in
    night) gamma="1.1:0.8:0.7";;
    light) gamma="1:1:1";;
    *)     exit 1;;
esac
for output in "${outputs[@]}";do
    xrandr --output "$output" --gamma "$gamma" --brightness "$brightness"
done

