#!/usr/bin/env bash
pane="$(tmux list-pane -F "#{pane_start_command} #{pane_pid}"\
| awk '/tmux-filetree/')"
([[ "$pane" = tmux-filetree* ]]\
&& pid="$(echo "$pane" | awk 'NR==1 { print $2 }')"\
&& kill "$pid"\
&& tmux last-pane)\
|| tmux split-window -h -l 35 -t 1 -b 'tmux-filetree'\
&& tmux last-pane

