#!/usr/bin/env bash
pane="$(tmux list-pane -F "#{pane_start_command} #{pane_pid}")"
filetree="$(echo "$pane" | awk '/tmux-filetree/')"
[[ "$filetree" = tmux-filetree* ]]\
&& kill "${filetree#* }"\
&& ( (( $(echo "$pane" | wc -l) == 2 )) || tmux last-pane )\
|| (
    tmux split-window -h -l 20 -t 1 -b 'tmux-filetree'\
    && tmux last-pane
)

