#!/usr/bin/env bash
# ~/.bashrc: executed by bash(0) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# -- env --
# colored GCC warnings and errors
# export GCC_COLORS="error=01;31"
# export GCC_COLORS="$GCC_COLORS:warning=01;35"
# export GCC_COLORS="$GCC_COLORS:note=01;36"
# export GCC_COLORS="$GCC_COLORS:caret=01;32"
# export GCC_COLORS="$GCC_COLORS:locus=01"
# export GCC_COLORS="$GCC_COLORS:quote=01S"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
DOT_PATH="$XDG_CONFIG_HOME/dot"
BASH_PATH="$DOT_PATH/bash"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR=vim
export PYTHONSTARTUP="$DOT_PATH/python/startup.py"
FZF_PATH="$DOT_PATH/fzf"
FZF_BIND="$FZF_BIND --bind ctrl-space:accept"
AG_OPTIONS="$AG_OPTIONS --no-color"
AG_OPTIONS="$AG_OPTIONS --hidden"
AG_OPTIONS="$AG_OPTIONS --path-to-ignore $FZF_HOME/ignore"
AG_OPTIONS="$AG_OPTIONS --unrestricted"
AG_OPTIONS="$AG_OPTIONS -g ''"
BAT_OPTIONS="$BAT_OPTIONS --color=always"
export FZF_DEFAULT_COMMAND="ag $AG_OPTIONS"
export FZF_PREVIEW="--preview 'bat {} $BAT_OPTIONS'"
export FZF_DEFAULT_OPTS="--reverse $FZF_BIND"
LSOPTIONS="$LSOPTIONS --color=always"
LSOPTIONS="$LSOPTIONS --almost-all"
LSOPTIONS="$LSOPTIONS --group-directories"
LSOPTIONS="$LSOPTIONS --sort=extension"
LSOPTIONS="$LSOPTIONS --human-readable"
PWDD='"$PWD"'
DKOPTIONS="-it"
DKOPTIONS="$DKOPTIONS --rm"
DKOPTIONS="$DKOPTIONS --user=$(id -u):$(id -g)"
DKOPTIONSNODE="$DKOPTIONS"
DKOPTIONSNODE="$DKOPTIONSNODE --name node-main"
DKOPTIONSNODE="$DKOPTIONSNODE --volume $PWDD:/usr/src/app"
DKOPTIONSNODE="$DKOPTIONSNODE --workdir /usr/src/app"
DKOPTIONSNODE="$DKOPTIONSNODE node"
DKOPTIONSSPOTIFYDL="$DKOPTIONS"
DKOPTIONSSPOTIFYDL="$DKOPTIONSSPOTIFYDL --volume $PWDD:/download"
DKOPTIONSYOUTUBEDL="$DKOPTIONS"
DKOPTIONSYOUTUBEDL="$DKOPTIONSYOUTUBEDL --volume $PWDD:/usr/src/app"
# DKOPTIONSGALLERYDL
# DKOPTIONSINSTALOOTER
export WGETRC="$DOT_PATH/wgetrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
# export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
export LESSHISTFILE=-
# INPUTRC=~/.config/dot/bash/inputrc
export TMUX_SCRIPT="$DOT_PATH/tmux/script"
export TMUX_FILETREE_COMMAND="ls -1 $LSOPTIONS \"\$(readlink -e %s)\""
YTDL_OPTIONS_FORMAT="%(title)s.%(ext)s"
eval "$(cat "$XDG_CONFIG_HOME/user-dirs.dirs")"
HISTSIZE=100
HISTFILESIZE=100
HISTFILE=~/.config/dot/bash/history-private
HISTIGNORE='history:ls:pwd:l:'
HISTTIMEFORMAT='%F, %T '
HISTCONTROL=ignoreboth:erasedups
PROMPT_COMMAND='history -a'
# -- util functions --
open() {
    local file="$1"
    if [[ -n "$file" ]];then
        xdg-open "$file" &> /dev/null &
        (( $? == 0 )) && disown
    else
        file="$(find -type f | fzf --height=50%)"
        # file="$(fzf --height=50%)"
        if [[ "$file" != "" ]];then
            xdg-open "$file" &> /dev/null &
            (( $? == 0 )) && disown
        fi
    fi
}

envup() {
    while IFS='=' read -r name value || [[ -n "$line" ]];do
        export "$name"="$value"
    done < ".env"
}

_docker_search() {
    local -r URL_BASE='https://hub.docker.com/search'
    local type="${2-image}"
    local url="$URL_BASE?q=$1&type=$type"
    open "$url"
}

yt() {
    local option="$1"
    local format="$2"
    local url
    local OPTIONS
    url="${3:-$(clipp)}"
    case "$option" in
        audio)
            OPTIONS="--extract-audio --audio-format $format"
        ;;
        video)
            OPTIONS="--format $format"
        ;;
        img)
            OPTIONS="--write-thumbnail --skip-download"
        ;;
        *)
            echo "option not found. Use audio, video or img"
            return 1
        ;;
    esac
    youtube-dl $OPTIONS "$url"
}

l() {
    if [[ -f "$1" ]];then
        # read a file
        bat "$1" || cat "$1"
    elif [[ -z "$1" ]];then
        # list all file
        ls -1 $LSOPTIONS
    else
        # list folder contents
        ls -1 $LSOPTIONS "$1"
    fi
}

prev_cd() {
    if [[ -n $1 ]];then
        local -i n=$1
        for ((i=1; i<=n; i++));do
            cd ..
        done
    else
        cd ..
    fi
}

tmux_start() {
    if [[ -n "$TMUX" ]];then
        echo "qué haces capo?"
        return 1
    fi
    local sessions
    local session
    sessions="$(tmux list-session -F '#{session_name}' 2> /dev/null)"
    session="$(echo "$sessions" | fzf --print-query)"
    session="$(echo "${session//*[$'\n']}")"
    if [[ -n "$session" ]];then
        tmux attach-session -t "$session" 2> /dev/null
        if (( $? != 0 ));then
            tmux new-session -s "$session" &> /dev/null
        fi
    fi
}

c() {
    local code='BEGIN { printf "%.2f", $request; exit }'
    local request="$1"
    request="${request//./}"
    request="${request//,/.}"
    result="$(awk "$code")"
    echo "$request=$result"
    echo "$result" | xclip -selection clipboard -in
}

v() {
    if [[ -n "$1" ]];then
        vim "$1"
    elif [[ -n "$TMUX" ]];then
        local file
        file="$(fzf-tmux -p)"\
        && vim "$file"
    else
        local file
        file="$(fzf)"\
        && vim "$file"
    fi
}

extract() {
     if [[ -f $1 ]]; then
         case $1 in
             *.tar.bz2)   tar xvjf $1    ;;
             *.tar.gz)    tar xvzf $1    ;;
             *.bz2)       bunzip2 $1     ;;
             *.rar)       unrar x $1     ;;
             *.gz)        gunzip $1      ;;
             *.tar)       tar xvf $1     ;;
             *.tbz2)      tar xvjf $1    ;;
             *.tgz)       tar xvzf $1    ;;
             *.zip)       unzip $1       ;;
             *.Z)         uncompress $1  ;;
             *.7z)        7z x $1        ;;
             *)           echo "'$1' cannot be extracted via >extract<" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

# -- alias --
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
alias ..='prev_cd'
alias clipc='xclip -selection clipboard -in'
alias clipp='xclip -selection clipboard -out'
alias d='docker'
alias date-now='date "+%T-%x" | tr ":/" "--"'
alias dc='docker-compose'
alias docker-search='_docker_search'
alias goo='googler -n 3'
alias ll="ls -l $LSOPTIONS"
alias node="docker run $DKOPTIONSNODE node"
alias npm="docker run $DKOPTIONSNODE npm"
alias pathget="find -type f | fzf | sed 's/^..//' | tr -d '\n' | clipc"
alias spotify-dl="docker run $DKOPTIONSSPOTIFYDL spotify-dl"
alias wget-clip='wget --continue "$(clipp)"'
alias youtube-dl="docker run $DKOPTIONSYOUTUBEDL youtube-dl"

# -- startup --

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [[ -z "${debian_chroot:-}" && -r /etc/debian_chroot ]];then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
# force_color_prompt=yes

if [[ -n "$force_color_prompt" ]];then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    if [[ -x /usr/bin/tput ]];then
        tput setaf 1 >& /dev/null
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [[ "$color_prompt" = yes ]];then
    PS1='${debian_chroot:+($debian_chroot)}'
    PS1="$PS1"'\[\033[01;32m\]\u@\h\[\033[00m\]:'
    PS1="$PS1"'\[\033[01;34m\]\w\[\033[00m\]'
    PS1="$PS1"'\n\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\n\$ '
fi

# unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
if [[ "$TERM" == xterm* || "$TERM" == rxvt* ]];then
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
fi


# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# append to the history file, don't overwrite it
shopt -s histappend

setxkbmap -layout us -variant altgr-intl
xinput disable "ILITEK ILITEK Multi-Touch"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]];then
        . /usr/share/bash-completion/bash_completion
    elif [[ -f /etc/bash_completion ]];then
        . /etc/bash_completion
    fi
fi

# enable color support of ls and also add handy aliases
if [[ -x /usr/bin/dircolors ]];then
    if [[ -r ~/.dircolors ]];then
        eval "$(dircolors --bourne-shell ~/.dircolors)"
    else
        eval "$(dircolors --bourne-shell)"
    fi
fi

if [[ $- == *i* ]];then
    for file in "$BASH_PATH/completion-"*;do
        . "$file"
    done
fi

for file in "$BASH_PATH/key-bindings-"*;do
    . "$file"
done

if [[ "$(tty)" = /dev/tty1 ]];then
    startx
fi

if [[ "$(tty)" == */pts/* ]];then
    if [[ -z "$TMUX" ]];then
        . "$XDG_CONFIG_HOME/dot/bash/tmux-session"
        tmux_start
    fi
fi

