#!/usr/bin/env bash

for folder in ~/w/*/;do
    name="${folder%%/}"
    name="${name##*/}"
    tmux has-session -t "$name" &> /dev/null || {
        tmux new-session -d -c "$folder" -t "$name"
    }
done
